import type { NextPage } from 'next'
import Forms from '../components/Form'
import Head from 'next/head'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<div className=" center" >
  <Forms />
</div>

    </div>


  )
}

export default Home
