import type { NextPage } from "next";
import Forms from "../components/form";
import Head from "next/head";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Search | AlgoAI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="first">
        <main>
          <div className="init">
            <div className="gap"></div>
            <div className="form" style={{ padding: "1rem" }}>
              <div className="intro">
                <div className="MuiBox-root css-10fo8i1">
                  <h2>Ask an algorithmic question</h2>
                </div>
                <div className="desc">
                  AlgoAI uses gpt3 codegen model to resolve your question.
                </div>
              </div>
              <Forms />
            </div>
            <div className="lowerSpace"></div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
